# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/october/test/models/user/columns.yaml

# Displays the list filter
filter: $/october/test/models/user/scopes.yaml

# Model Class name
modelClass: October\Test\Models\User

# List Title
title: Manage Users

# Link URL for each record
recordUrl: october/test/users/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: updated_at
    direction: desc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

